### ISSUE TITLE
Core Pagination Functionality Unit Test

### ISSUE THREAD

**Issue by BeckyWu220** [Twotalltotems/react-native-paginatable#13]
Test the two core functionalities, which are loadMore and refresh in the PaginatableList. In order to achieve the testing, mock-up API responses need to be used in the test. 

- [ ] When loadMore method is called, mock-up API response, and check if the API call is properly called once with the correct parameters (pageNumber, pageSize, headers).
- [ ]  If onLoadMore props exist, test the value of onLoadMore, which is a function, is called properly with correct params (including additional query params). 

- [ ] When refresh method is called, mock-up API response, and check if the API call is made with the first page, along with correct parameters(pageSize, headers). 
- [ ] When onRefresh props exist, test the value of onRefresh to be called with proper params(pageSize, headers, additional query params).

**Comment by sunkibaek** [comment]
@BeckyWu220 I would like to take this one if no one is working on it 😄

**Comment by BeckyWu220** [comment]
@sunkibaek Sounds great! Thanks for offering. We internally had something for this section too, maybe we could combine the test later after you are done. Looking forward to your PR. Thanks again for your contribution to the last PR.
